In [2]:
import pandas as pd

#Archivos a utilizar para la revision con el listado del barco:
#-Concentrado2
concentrado2 = '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/Concentrado2_SoloEnero2026.xlsx'

#-FacturasFaltantes
facturasFaltantes = '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/Facturas_Faltantes_SoloEnero2026.xlsx'

#-ExtraccionHistorica
Extraccion = '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/ExtraccionGeneral2Enero2026.xlsx'
#-ChasisBarcoEJEMPLO
chasisBarco = '/Users/jorgevilchis/Downloads/chasis de barco SIEM CICERO 30.09.2025.xlsx'


dfConcentrado2 = pd.read_excel(concentrado2)
dfFacturasFaltantes = pd.read_excel(facturasFaltantes)
dfExtraccion = pd.read_excel(Extraccion)
dfChasisBarco = pd.read_excel(chasisBarco)
#Queremos ver que tenemos, que no, y las que no en donde es que estaban. 

print('Concentrado2:')
dfConcentrado2.head(10)
print('---'*20)
print('FacturasFaltantes:')
dfFacturasFaltantes.head(3)
print('---'*20)
print('ExtraccionHistorica:')
dfExtraccion.head(3)
print('---'*20) 
print('ChasisBarco:')
dfChasisBarco.head(3)
print('---'*20)

Concentrado2:
------------------------------------------------------------
FacturasFaltantes:
------------------------------------------------------------
ExtraccionHistorica:
------------------------------------------------------------
ChasisBarco:
------------------------------------------------------------

In [4]:
# === STEP 1: Load all boat manifest files ===
from pathlib import Path

boat_files = [
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/Facturas/Attachments-FW_ (VWKL) MV EMDEN V.029A - ATD BCN 30_12_25 - CARGO DOCUMENTATION BARCELONA/chasis de barco EMDEN 23.01.2026.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/SoloDiciembre/Attachments-FW_ Mexico Waybills _Wolfsburg_ 028A (1)/Chasis de barco WOLFSBURG 10.12.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/Previas/fwmexicowaybillssiemconfucius071a/Chasis de barco SIEM CONFUCIUS 01.12.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/Previas/fwmexicowaybillslakevictoria001a/Chasis de barco LAKE VICTORIA 03.11.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Octubre2025/FacturasPeriodoOctubre/fwmexicowaybillssiemcicero110a/chasis de barco SIEM CICERO 30.09.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/Previas/fwmxwaybillsemden027a (1)/Chasis de barco EMDEN 14.11.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Agosto2025/Facturas/fwmexicowaybillswayforward010a_SinErrror/chasis de barco WAY FORWARD 12.08.2024.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/trashbuffer/fw20231233mexicohamburghighway031223/Chasis de barco HAMBURG HIGHWAY 28.12.2023.xlsx',
]

# Load and combine all boat manifests
all_boats = []
for f in boat_files:
    try:
        df = pd.read_excel(f)
        df['SourceFile'] = Path(f).name
        df['FolderPath'] = str(Path(f).parent)
        all_boats.append(df)
        print(f"[OK] Loaded: {Path(f).name} ({len(df)} rows)")
    except Exception as e:
        print(f"[ERROR] Loading {Path(f).name}: {e}")

dfAllBoats = pd.concat(all_boats, ignore_index=True)
print(f"\nTotal boat records: {len(dfAllBoats)}")
print(f"Unique boats: {dfAllBoats['Ship Name'].nunique()}")
dfAllBoats['Ship Name'].value_counts()

[OK] Loaded: chasis de barco EMDEN 23.01.2026.xlsx (1613 rows)
[OK] Loaded: Chasis de barco WOLFSBURG 10.12.2025.xlsx (122 rows)
[OK] Loaded: Chasis de barco SIEM CONFUCIUS 01.12.2025.xlsx (65 rows)
[OK] Loaded: Chasis de barco LAKE VICTORIA 03.11.2025.xlsx (70 rows)
[OK] Loaded: chasis de barco SIEM CICERO 30.09.2025.xlsx (98 rows)
[OK] Loaded: Chasis de barco EMDEN 14.11.2025.xlsx (965 rows)
[OK] Loaded: chasis de barco WAY FORWARD 12.08.2024.xlsx (1476 rows)
[OK] Loaded: Chasis de barco HAMBURG HIGHWAY 28.12.2023.xlsx (1050 rows)

Total boat records: 5459
Unique boats: 7

Ship Name
EMDEN              2578
WAY FORWARD        1476
HAMBURG HIGHWAY    1050
WOLFSBURG           122
SIEM CICERO          98
LAKE VICTORIA        70
SIEM CONFUCIUS       65
Name: count, dtype: int64

In [ ]:
# === STEP 2: Match FacturasFaltantes with boat data via Invoice Number ===

# Clean invoice columns for matching
dfFacturasFaltantes['FACT'] = dfFacturasFaltantes['FACT'].astype(str).str.strip()
dfAllBoats['FI: Invoice No.'] = dfAllBoats['FI: Invoice No.'].astype(str).str.strip()

# Match missing invoices to boats
dfFaltantesConBarco = dfFacturasFaltantes.merge(
    dfAllBoats[['FI: Invoice No.', 'Ship Name', 'Chassis Number', 'FolderPath']].drop_duplicates(),
    left_on='FACT',
    right_on='FI: Invoice No.',
    how='left'
)

# Count matches
matched = dfFaltantesConBarco['Ship Name'].notna().sum()
total = len(dfFaltantesConBarco)
print(f"Matched via Invoice: {matched}/{total} ({matched/total*100:.1f}%)")
print(f"\nBoats found in missing invoices:")
print(dfFaltantesConBarco[dfFaltantesConBarco['Ship Name'].notna()]['Ship Name'].value_counts())

NameError: name 'dfFacturasFaltantes' is not defined

In [5]:
# === STEP 3: For unmatched invoices, try matching via Chassis from dfExtraccion ===

# Get the invoices that weren't matched by invoice number
unmatched_invoices = dfFaltantesConBarco[dfFaltantesConBarco['Ship Name'].isna()]['FACT'].unique()
print(f"Trying to match {len(unmatched_invoices)} unmatched invoices via chassis...")

# Get chassis for these invoices from dfExtraccion
dfExtraccion['Factura'] = dfExtraccion['Factura'].astype(str).str.strip()
dfExtraccion['Chasis'] = dfExtraccion['Chasis'].astype(str).str.strip()
dfAllBoats['Chassis Number'] = dfAllBoats['Chassis Number'].astype(str).str.strip()

# Get unique invoice-chassis pairs from extraction
extraccion_subset = dfExtraccion[dfExtraccion['Factura'].isin(unmatched_invoices)][['Factura', 'Chasis']].drop_duplicates()

# Match these chassis against boat manifests
chassis_boat_match = extraccion_subset.merge(
    dfAllBoats[['Chassis Number', 'Ship Name', 'FolderPath']].drop_duplicates(),
    left_on='Chasis',
    right_on='Chassis Number',
    how='inner'
)

print(f"[OK] Found {len(chassis_boat_match)} additional matches via chassis")
if len(chassis_boat_match) > 0:
    print(f"\nAdditional boats found:")
    print(chassis_boat_match['Ship Name'].value_counts())

Trying to match 457 unmatched invoices via chassis...
[OK] Found 0 additional matches via chassis

In [6]:
# === STEP 4: Create Final Report ===

# Combine both matching methods
# First: direct invoice matches
direct_matches = dfFaltantesConBarco[dfFaltantesConBarco['Ship Name'].notna()][['FACT', 'Ship Name', 'FolderPath']].drop_duplicates()
direct_matches['Match Type'] = 'Invoice Number'

# Second: chassis matches (rename column)
chassis_matches = chassis_boat_match[['Factura', 'Ship Name', 'FolderPath']].drop_duplicates()
chassis_matches = chassis_matches.rename(columns={'Factura': 'FACT'})
chassis_matches['Match Type'] = 'Chassis'

# Combine
all_matches = pd.concat([direct_matches, chassis_matches], ignore_index=True).drop_duplicates(subset='FACT')

# Check which invoices exist in dfExtraccion (PDF was processed)
all_matches['Found in Extraccion'] = all_matches['FACT'].isin(dfExtraccion['Factura'].astype(str))

# Add the still-unmatched invoices
all_faltantes = dfFacturasFaltantes['FACT'].unique()
matched_faltantes = all_matches['FACT'].unique()
still_missing = [f for f in all_faltantes if f not in matched_faltantes]

# Create unmatched dataframe
unmatched_df = pd.DataFrame({'FACT': still_missing})
unmatched_df['Ship Name'] = 'NOT FOUND IN BOATS'
unmatched_df['FolderPath'] = 'UNKNOWN'
unmatched_df['Match Type'] = 'No Match'
unmatched_df['Found in Extraccion'] = unmatched_df['FACT'].isin(dfExtraccion['Factura'].astype(str))

# Final report
dfFinalReport = pd.concat([all_matches, unmatched_df], ignore_index=True)

print("=" * 60)
print("FINAL REPORT: FacturasFaltantes by Boat")
print("=" * 60)
print(f"\nTotal missing invoices: {len(dfFacturasFaltantes)}")
print(f"Matched to boats: {len(all_matches)}")
print(f"Not found in any boat: {len(still_missing)}")
print(f"\nBreakdown by Boat:")
print(dfFinalReport['Ship Name'].value_counts())
print(f"\nFiles found in extraction: {dfFinalReport['Found in Extraccion'].sum()}")
dfFinalReport.head(20)

============================================================
FINAL REPORT: FacturasFaltantes by Boat
============================================================

Total missing invoices: 458
Matched to boats: 1
Not found in any boat: 457

Breakdown by Boat:
Ship Name
NOT FOUND IN BOATS    457
SIEM CONFUCIUS          1
Name: count, dtype: int64

Files found in extraction: 1

,FACT,Ship Name,FolderPath,Match Type,Found in Extraccion
0,953325E,SIEM CONFUCIUS,/Users/jorgevilchis/Documents/Cosas Gestell/Ad...,Invoice Number,False
1,20523011,NOT FOUND IN BOATS,UNKNOWN,No Match,False
2,20523012,NOT FOUND IN BOATS,UNKNOWN,No Match,False
3,20523013,NOT FOUND IN BOATS,UNKNOWN,No Match,False
4,13017050,NOT FOUND IN BOATS,UNKNOWN,No Match,False
5,979617E,NOT FOUND IN BOATS,UNKNOWN,No Match,False
6,67073037,NOT FOUND IN BOATS,UNKNOWN,No Match,False
7,67073036,NOT FOUND IN BOATS,UNKNOWN,No Match,False
8,67073039,NOT FOUND IN BOATS,UNKNOWN,No Match,False
9,67073038,NOT FOUND IN BOATS,UNKNOWN,No Match,False
10,67074953,NOT FOUND IN BOATS,UNKNOWN,No Match,False
11,67074915,NOT FOUND IN BOATS,UNKNOWN,No Match,False
12,67074907,NOT FOUND IN BOATS,UNKNOWN,No Match,False
13,67074955,NOT FOUND IN BOATS,UNKNOWN,No Match,False
14,67074906,NOT FOUND IN BOATS,UNKNOWN,No Match,False
15,67074898,NOT FOUND IN BOATS,UNKNOWN,No Match,False
16,67074954,NOT FOUND IN BOATS,UNKNOWN,No Match,False
17,67074952,NOT FOUND IN BOATS,UNKNOWN,No Match,False
18,67074941,NOT FOUND IN BOATS,UNKNOWN,No Match,False
19,67074980,NOT FOUND IN BOATS,UNKNOWN,No Match,False

In [7]:
# === STEP 5: Export Report & Show Where to Find Files ===

# Save report to Excel
output_path = '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/FacturasFaltantes_ConBarco.xlsx'
dfFinalReport.to_excel(output_path, index=False)
print(f"Report saved to: {output_path}")

# Show unique folder paths where to find missing files
print("\n" + "=" * 60)
print("WHERE TO FIND THE MISSING FILES:")
print("=" * 60)

for boat, group in dfFinalReport[dfFinalReport['Ship Name'] != 'NOT FOUND IN BOATS'].groupby('Ship Name'):
    folder = group['FolderPath'].iloc[0]
    count = len(group)
    print(f"\n{boat} ({count} invoices):")
    print(f"   {folder}")

# Show invoices not found in any boat
not_in_boats = dfFinalReport[dfFinalReport['Ship Name'] == 'NOT FOUND IN BOATS']
if len(not_in_boats) > 0:
    print(f"\n[WARNING] {len(not_in_boats)} invoices NOT FOUND in any boat manifest:")
    print(not_in_boats['FACT'].tolist()[:20])
    if len(not_in_boats) > 20:
        print(f"   ... and {len(not_in_boats) - 20} more")

Report saved to: /Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/FacturasFaltantes_ConBarco.xlsx

============================================================
WHERE TO FIND THE MISSING FILES:
============================================================

SIEM CONFUCIUS (1 invoices):
   /Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/Previas/fwmexicowaybillssiemconfucius071a

[WARNING] 457 invoices NOT FOUND in any boat manifest:
['20523011', '20523012', '20523013', '13017050', '979617E', '67073037', '67073036', '67073039', '67073038', '67074953', '67074915', '67074907', '67074955', '67074906', '67074898', '67074954', '67074952', '67074941', '67074980', '67074964']
   ... and 437 more

In [8]:
# === FUNCTION: Find chassis from boats NOT in Extraccion ===

def find_missing_chassis_from_boats(dfBoats, dfExtraccion):
    """
    Finds chassis numbers from boat manifests that do not appear in the extraction.
    
    Parameters:
    - dfBoats: DataFrame with boat manifest data (must have 'Chassis Number' and 'Ship Name')
    - dfExtraccion: DataFrame with extraction data (must have 'Chasis')
    
    Returns:
    - DataFrame with missing chassis and their boat information
    """
    # Clean chassis columns
    boats_chassis = dfBoats['Chassis Number'].astype(str).str.strip().unique()
    extraccion_chassis = dfExtraccion['Chasis'].astype(str).str.strip().unique()
    
    # Find chassis in boats but NOT in extraccion
    missing_chassis = set(boats_chassis) - set(extraccion_chassis)
    
    # Get full info for missing chassis
    dfBoats_clean = dfBoats.copy()
    dfBoats_clean['Chassis Number'] = dfBoats_clean['Chassis Number'].astype(str).str.strip()
    
    dfMissing = dfBoats_clean[dfBoats_clean['Chassis Number'].isin(missing_chassis)].copy()
    
    print("=" * 60)
    print("CHASSIS FROM BOATS NOT FOUND IN EXTRACCION")
    print("=" * 60)
    print(f"\nTotal chassis in boat manifests: {len(boats_chassis)}")
    print(f"Total chassis in extraccion: {len(extraccion_chassis)}")
    print(f"Missing from extraccion: {len(missing_chassis)}")
    print(f"\nBreakdown by boat:")
    print(dfMissing['Ship Name'].value_counts())
    
    return dfMissing

# Run the function
dfMissingFromBoats = find_missing_chassis_from_boats(dfAllBoats, dfExtraccion)
dfMissingFromBoats.head(20)

============================================================
CHASSIS FROM BOATS NOT FOUND IN EXTRACCION
============================================================

Total chassis in boat manifests: 5459
Total chassis in extraccion: 149804
Missing from extraccion: 2

Breakdown by boat:
Ship Name
SIEM CONFUCIUS    2
Name: count, dtype: int64

,Chassis Number,Model,Ship Name,FI: Invoice No.,estatus,SourceFile,FolderPath,Estatus
1741,VSSBBAKP9T1019386,KP1CYS,SIEM CONFUCIUS,953325E,NaN,Chasis de barco SIEM CONFUCIUS 01.12.2025.xlsx,/Users/jorgevilchis/Documents/Cosas Gestell/Ad...,ok
1742,VSSAAAKP0T1019405,KP1BC5,SIEM CONFUCIUS,953344E,NaN,Chasis de barco SIEM CONFUCIUS 01.12.2025.xlsx,/Users/jorgevilchis/Documents/Cosas Gestell/Ad...,ok

In [9]:
# === FUNCTION: Check if invoices from missing chassis exist in Extraccion ===

def check_invoices_in_extraccion(dfMissing, dfExtraccion):
    """
    Checks if invoices associated with missing chassis exist in the extraction.
    Helps identify if the PDF was processed but chassis wasn't extracted,
    or if the entire invoice PDF is missing.
    
    Returns:
    - Tuple of (dfInvoiceFound, dfInvoiceNotFound)
    """
    dfMissing_clean = dfMissing.copy()
    dfMissing_clean['FI: Invoice No.'] = dfMissing_clean['FI: Invoice No.'].astype(str).str.strip()
    
    extraccion_invoices = dfExtraccion['Factura'].astype(str).str.strip().unique()
    
    dfMissing_clean['Invoice in Extraccion'] = dfMissing_clean['FI: Invoice No.'].isin(extraccion_invoices)
    
    dfInvoiceFound = dfMissing_clean[dfMissing_clean['Invoice in Extraccion'] == True].copy()
    dfInvoiceNotFound = dfMissing_clean[dfMissing_clean['Invoice in Extraccion'] == False].copy()
    
    print("=" * 60)
    print("INVOICE STATUS FOR MISSING CHASSIS")
    print("=" * 60)
    print(f"\nTotal missing chassis records: {len(dfMissing_clean)}")
    print(f"Unique invoices in missing chassis: {dfMissing_clean['FI: Invoice No.'].nunique()}")
    print(f"\nInvoices FOUND in extraccion: {dfInvoiceFound['FI: Invoice No.'].nunique()}")
    print("  -> Chassis missing but invoice PDF was processed")
    print(f"\nInvoices NOT FOUND in extraccion: {dfInvoiceNotFound['FI: Invoice No.'].nunique()}")
    print("  -> Entire invoice PDF is missing")
    
    if len(dfInvoiceNotFound) > 0:
        print(f"\nMissing invoices by boat:")
        print(dfInvoiceNotFound.groupby('Ship Name')['FI: Invoice No.'].nunique())
    
    return dfInvoiceFound, dfInvoiceNotFound

# Run the function
dfChassisFound, dfChassisNotFound = check_invoices_in_extraccion(dfMissingFromBoats, dfExtraccion)

# Show invoices that need to be located
print("\n" + "=" * 60)
print("INVOICES TO LOCATE (PDF not processed):")
print("=" * 60)
if len(dfChassisNotFound) > 0:
    missing_invoices = dfChassisNotFound[['FI: Invoice No.', 'Ship Name', 'FolderPath']].drop_duplicates()
    print(missing_invoices)

============================================================
INVOICE STATUS FOR MISSING CHASSIS
============================================================

Total missing chassis records: 2
Unique invoices in missing chassis: 2

Invoices FOUND in extraccion: 0
  -> Chassis missing but invoice PDF was processed

Invoices NOT FOUND in extraccion: 2
  -> Entire invoice PDF is missing

Missing invoices by boat:
Ship Name
SIEM CONFUCIUS    2
Name: FI: Invoice No., dtype: int64

============================================================
INVOICES TO LOCATE (PDF not processed):
============================================================
     FI: Invoice No.       Ship Name  \
1741         953325E  SIEM CONFUCIUS
1742         953344E  SIEM CONFUCIUS

                                             FolderPath
1741  /Users/jorgevilchis/Documents/Cosas Gestell/Ad...
1742  /Users/jorgevilchis/Documents/Cosas Gestell/Ad...

In [10]:
# === FUNCTION: Check FacturasFaltantes against Extraccion ===

def check_facturas_faltantes_in_extraccion(dfFaltantes, dfExtraccion):
    """
    Checks if the missing invoices (FacturasFaltantes) exist in the extraction.
    
    Returns:
    - Tuple of (dfFound, dfNotFound)
    """
    dfFaltantes_clean = dfFaltantes.copy()
    dfFaltantes_clean['FACT'] = dfFaltantes_clean['FACT'].astype(str).str.strip()
    
    extraccion_invoices = dfExtraccion['Factura'].astype(str).str.strip().unique()
    
    dfFaltantes_clean['In Extraccion'] = dfFaltantes_clean['FACT'].isin(extraccion_invoices)
    
    dfFound = dfFaltantes_clean[dfFaltantes_clean['In Extraccion'] == True].copy()
    dfNotFound = dfFaltantes_clean[dfFaltantes_clean['In Extraccion'] == False].copy()
    
    print("=" * 60)
    print("FACTURAS FALTANTES vs EXTRACCION")
    print("=" * 60)
    print(f"\nTotal FacturasFaltantes: {len(dfFaltantes_clean)}")
    print(f"\nFOUND in extraccion: {len(dfFound)}")
    print("  -> PDF was processed, J y N should be available")
    print(f"\nNOT FOUND in extraccion: {len(dfNotFound)}")
    print("  -> PDF was never processed, need to locate files")
    
    return dfFound, dfNotFound

# Run the function
dfFaltantesFound, dfFaltantesNotFound = check_facturas_faltantes_in_extraccion(dfFacturasFaltantes, dfExtraccion)

print("\n" + "=" * 60)
print("FACTURAS FALTANTES NOT IN EXTRACCION:")
print("=" * 60)
print(dfFaltantesNotFound['FACT'].tolist()[:30])
if len(dfFaltantesNotFound) > 30:
    print(f"... and {len(dfFaltantesNotFound) - 30} more")

============================================================
FACTURAS FALTANTES vs EXTRACCION
============================================================

Total FacturasFaltantes: 458

FOUND in extraccion: 1
  -> PDF was processed, J y N should be available

NOT FOUND in extraccion: 457
  -> PDF was never processed, need to locate files

============================================================
FACTURAS FALTANTES NOT IN EXTRACCION:
============================================================
['20523011', '20523012', '20523013', '13017050', '979617E', '67073037', '67073036', '67073039', '67073038', '67074953', '67074915', '67074907', '67074955', '67074906', '67074898', '67074954', '67074952', '67074941', '67074980', '67074964', '67074899', '67074864', '67075015', '67075030', '67075067', '67074987', '67075050', '67075044', '67075092', '67075037']
... and 427 more

In [11]:
# === FUNCTION: Check FacturasFaltantes against Boat Manifests ===

def check_facturas_faltantes_in_boats(dfFaltantes, dfBoats):
    """
    Checks if the missing invoices (FacturasFaltantes) appear in boat manifests.
    
    Returns:
    - Tuple of (dfFoundInBoats, dfNotFoundInBoats)
    """
    dfFaltantes_clean = dfFaltantes.copy()
    dfFaltantes_clean['FACT'] = dfFaltantes_clean['FACT'].astype(str).str.strip()
    
    boat_invoices = dfBoats['FI: Invoice No.'].astype(str).str.strip().unique()
    
    dfFaltantes_clean['In Boats'] = dfFaltantes_clean['FACT'].isin(boat_invoices)
    
    dfFoundInBoats = dfFaltantes_clean[dfFaltantes_clean['In Boats'] == True].copy()
    dfNotFoundInBoats = dfFaltantes_clean[dfFaltantes_clean['In Boats'] == False].copy()
    
    # Get boat info for found invoices
    if len(dfFoundInBoats) > 0:
        dfFoundInBoats = dfFoundInBoats.merge(
            dfBoats[['FI: Invoice No.', 'Ship Name', 'FolderPath']].drop_duplicates(),
            left_on='FACT',
            right_on='FI: Invoice No.',
            how='left'
        )
    
    print("=" * 60)
    print("FACTURAS FALTANTES vs BOAT MANIFESTS")
    print("=" * 60)
    print(f"\nTotal FacturasFaltantes: {len(dfFaltantes_clean)}")
    print(f"\nFOUND in boat manifests: {len(dfFoundInBoats)}")
    if len(dfFoundInBoats) > 0:
        print("  Breakdown by boat:")
        print(dfFoundInBoats['Ship Name'].value_counts())
    print(f"\nNOT FOUND in any boat manifest: {len(dfNotFoundInBoats)}")
    
    return dfFoundInBoats, dfNotFoundInBoats

# Run the function
dfFaltantesInBoats, dfFaltantesNotInBoats = check_facturas_faltantes_in_boats(dfFacturasFaltantes, dfAllBoats)

# Show where to find the invoices that ARE in boats
if len(dfFaltantesInBoats) > 0:
    print("\n" + "=" * 60)
    print("WHERE TO FIND THESE INVOICES:")
    print("=" * 60)
    for boat, group in dfFaltantesInBoats.groupby('Ship Name'):
        folder = group['FolderPath'].iloc[0]
        invoices = group['FACT'].unique()
        print(f"\n{boat} ({len(invoices)} invoices):")
        print(f"   Folder: {folder}")
        print(f"   Invoices: {list(invoices)[:10]}")
        if len(invoices) > 10:
            print(f"   ... and {len(invoices) - 10} more")

============================================================
FACTURAS FALTANTES vs BOAT MANIFESTS
============================================================

Total FacturasFaltantes: 458

FOUND in boat manifests: 1
  Breakdown by boat:
Ship Name
SIEM CONFUCIUS    1
Name: count, dtype: int64

NOT FOUND in any boat manifest: 457

============================================================
WHERE TO FIND THESE INVOICES:
============================================================

SIEM CONFUCIUS (1 invoices):
   Folder: /Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/Previas/fwmexicowaybillssiemconfucius071a
   Invoices: ['953325E']

In [16]:
dfAllBoats.columns

Index(['Chassis Number', 'Model', 'Ship Name', 'FI: Invoice No.', 'estatus',
       'SourceFile', 'FolderPath', 'Estatus'],
      dtype='object')

In [19]:
from boat_analysis import *
# === STEP 1: Load all boat manifest files ===
from pathlib import Path

boat_files = [
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/Facturas/Attachments-FW_ (VWKL) MV EMDEN V.029A - ATD BCN 30_12_25 - CARGO DOCUMENTATION BARCELONA/chasis de barco EMDEN 23.01.2026.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/SoloDiciembre/Attachments-FW_ Mexico Waybills _Wolfsburg_ 028A (1)/Chasis de barco WOLFSBURG 10.12.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/Previas/fwmexicowaybillssiemconfucius071a/Chasis de barco SIEM CONFUCIUS 01.12.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/Previas/fwmexicowaybillslakevictoria001a/Chasis de barco LAKE VICTORIA 03.11.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Octubre2025/FacturasPeriodoOctubre/fwmexicowaybillssiemcicero110a/chasis de barco SIEM CICERO 30.09.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Diciembre 2025/Facturas/Previas/fwmxwaybillsemden027a (1)/Chasis de barco EMDEN 14.11.2025.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/Agosto2025/Facturas/fwmexicowaybillswayforward010a_SinErrror/chasis de barco WAY FORWARD 12.08.2024.xlsx',
    '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2025/trashbuffer/fw20231233mexicohamburghighway031223/Chasis de barco HAMBURG HIGHWAY 28.12.2023.xlsx',
]

#Archivos a utilizar para la revision con el listado del barco:
#-Concentrado2
concentrado2 = '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/Concentrado2_SoloEnero2026.xlsx'

#-FacturasFaltantes
facturasFaltantes = '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/Facturas_Faltantes_SoloEnero2026.xlsx'

#-ExtraccionHistorica
Extraccion = '/Users/jorgevilchis/Documents/Cosas Gestell/Aduanas1/P1 - PDFs/2026/Enero/ExtraccionGeneral2Enero2026.xlsx'
#-ChasisBarcoEJEMPLO
chasisBarco = '/Users/jorgevilchis/Downloads/chasis de barco SIEM CICERO 30.09.2025.xlsx'


dfConcentrado2 = pd.read_excel(concentrado2)
dfFacturasFaltantes = pd.read_excel(facturasFaltantes)
dfExtraccion = pd.read_excel(Extraccion)
dfChasisBarco = pd.read_excel(chasisBarco)
#Queremos ver que tenemos, que no, y las que no en donde es que estaban. 


# Load and combine all boat manifests
all_boats = []
for f in boat_files:
    try:
        df = pd.read_excel(f)
        df['SourceFile'] = Path(f).name
        df['FolderPath'] = str(Path(f).parent)
        all_boats.append(df)
        print(f"[OK] Loaded: {Path(f).name} ({len(df)} rows)")
    except Exception as e:
        print(f"[ERROR] Loading {Path(f).name}: {e}")

dfAllBoats = pd.concat(all_boats, ignore_index=True)
print(f"\nTotal boat records: {len(dfAllBoats)}")
print(f"Unique boats: {dfAllBoats['Ship Name'].nunique()}")
dfAllBoats['Ship Name'].value_counts()
# Load data
df_boats = load_boat_manifests(boat_files)

# Run everything
results = run_full_analysis(df_boats, dfExtraccion, dfFacturasFaltantes)

[OK] Loaded: chasis de barco EMDEN 23.01.2026.xlsx (1613 rows)
[OK] Loaded: Chasis de barco WOLFSBURG 10.12.2025.xlsx (122 rows)
[OK] Loaded: Chasis de barco SIEM CONFUCIUS 01.12.2025.xlsx (65 rows)
[OK] Loaded: Chasis de barco LAKE VICTORIA 03.11.2025.xlsx (70 rows)
[OK] Loaded: chasis de barco SIEM CICERO 30.09.2025.xlsx (98 rows)
[OK] Loaded: Chasis de barco EMDEN 14.11.2025.xlsx (965 rows)
[OK] Loaded: chasis de barco WAY FORWARD 12.08.2024.xlsx (1476 rows)
[OK] Loaded: Chasis de barco HAMBURG HIGHWAY 28.12.2023.xlsx (1050 rows)

Total boat records: 5459
Unique boats: 7
[OK] chasis de barco EMDEN 23.01.2026.xlsx (1613 rows)
[OK] Chasis de barco WOLFSBURG 10.12.2025.xlsx (122 rows)
[OK] Chasis de barco SIEM CONFUCIUS 01.12.2025.xlsx (65 rows)
[OK] Chasis de barco LAKE VICTORIA 03.11.2025.xlsx (70 rows)
[OK] chasis de barco SIEM CICERO 30.09.2025.xlsx (98 rows)
[OK] Chasis de barco EMDEN 14.11.2025.xlsx (965 rows)
[OK] chasis de barco WAY FORWARD 12.08.2024.xlsx (1476 rows)
[OK] Chasis de barco HAMBURG HIGHWAY 28.12.2023.xlsx (1050 rows)

[1/5] Chassis in boats vs extraction...
================================================================================
CHASSIS FROM BOATS vs EXTRACCION
================================================================================

[MATCHED] 5457 chassis FOUND in extraccion:
--------------------------------------------------------------------------------
FI: Invoice No.    Chassis Number       Ship Name
        N030836 VSSCE6KJ2TR562651           EMDEN
        N030836 VSSCE6KJ8TR562654           EMDEN
        N030836 VSSCE6KJXTR562123           EMDEN
        N030836 VSSCE6KJ4TR562649           EMDEN
        N030837 VSSBE6KJ1TR568355           EMDEN
        N030837 VSSBE6KJ2TR563293           EMDEN
        N030837 VSSBE6KJ2TR565142           EMDEN
        N030837 VSSBE6KJ1TR570302           EMDEN
        N030837 VSSBE6KJ3TR567191           EMDEN
        N030837 VSSBE6KJ0TR567410           EMDEN
        N030837 VSSBE6KJ2TR564878           EMDEN
        N030837 VSSBE6KJ0TR567407           EMDEN
        N030837 VSSBE6KJ2TR567358           EMDEN
        N030837 VSSBE6KJ0TR568704           EMDEN
        N030837 VSSBE6KJ3TR567403           EMDEN
        N030837 VSSBE6KJ1TR567111           EMDEN
        N030837 VSSBE6KJ3TR564484           EMDEN
        N030837 VSSBE6KJ0TR564748           EMDEN
        N030837 VSSBE6KJ0TR565060           EMDEN
        N030837 VSSBE6KJ1TR565844           EMDEN
        N030837 VSSBE6KJ0TR567956           EMDEN
        N030837 VSSBE6KJ3TR565067           EMDEN
        N030837 VSSBE6KJ1TR563253           EMDEN
        N030837 VSSBE6KJ1TR565505           EMDEN
        N030837 VSSBE6KJ1TR569523           EMDEN
        N030837 VSSBE6KJ1TR566766           EMDEN
        N030837 VSSBE6KJ0TR570324           EMDEN
        N030837 VSSBE6KJ0TR563163           EMDEN
        N030837 VSSBE6KJ3TR567420           EMDEN
        N030837 VSSBE6KJ2TR563858           EMDEN
        N030837 VSSBE6KJ1TR563205           EMDEN
        N030837 VSSBE6KJ1TR565083           EMDEN
        N030837 VSSBE6KJ2TR564508           EMDEN
        N030837 VSSBE6KJ2TR567781           EMDEN
        N030837 VSSBE6KJ2TR565450           EMDEN
        N030837 VSSBE6KJ2TR570468           EMDEN
        N030837 VSSBE6KJ0TR568329           EMDEN
        N030837 VSSBE6KJ2TR568252           EMDEN
        N030837 VSSBE6KJ2TR565772           EMDEN
        N030837 VSSBE6KJ0TR569612           EMDEN
        N030837 VSSBE6KJ0TR567049           EMDEN
        N030837 VSSBE6KJ0TR564071           EMDEN
        N030837 VSSBE6KJ2TR568428           EMDEN
        N030837 VSSBE6KJ0TR570145           EMDEN
        N030837 VSSBE6KJ1TR569098           EMDEN
        N030837 VSSBE6KJ0TR563972           EMDEN
        N030837 VSSBE6KJ1TR567139           EMDEN
        N030837 VSSBE6KJ0TR568914           EMDEN
        N030837 VSSBE6KJ0TR564510           EMDEN
        N030837 VSSBE6KJ2TR566694           EMDEN
        N030837 VSSBE6KJ2TR569742           EMDEN
        N030837 VSSBE6KJ0TR568315           EMDEN
        N030837 VSSBE6KJ2TR568624           EMDEN
        N030837 VSSBE6KJ1TR569537           EMDEN
        N030837 VSSBE6KJ2TR567795           EMDEN
        N030837 VSSBE6KJ3TR566333           EMDEN
        N030837 VSSBE6KJ1TR564533           EMDEN
        N030837 VSSBE6KJ1TR568369           EMDEN
        N030837 VSSBE6KJ0TR564958           EMDEN
        N030837 VSSBE6KJ2TR568560           EMDEN
        N030837 VSSBE6KJ2TR569093           EMDEN
        N030837 VSSBE6KJ0TR569173           EMDEN
        N030837 VSSBE6KJ3TR566297           EMDEN
        N030837 VSSBE6KJ1TR566282           EMDEN
        N030837 VSSBE6KJ2TR566324           EMDEN
        N030837 VSSBE6KJ1TR568565           EMDEN
        N030837 VSSBE6KJ0TR567164           EMDEN
        N030837 VSSBE6KJ3TR566302           EMDEN
        N030837 VSSBE6KJ0TR570422           EMDEN
        N030837 VSSBE6KJ1TR563222           EMDEN
        N030837 VSSBE6KJ0TR566290           EMDEN
        N030837 VSSBE6KJ2TR568994           EMDEN
        N030837 VSSBE6KJ3TR567384           EMDEN
        N030837 VSSBE6KJ0TR567908           EMDEN
        N030838 VSSBE6KJ5TR564597           EMDEN
        N030838 VSSBE6KJ5TR569623           EMDEN
        N030838 VSSBE6KJ7TR563662           EMDEN
        N030838 VSSBE6KJ4TR568608           EMDEN
        N030838 VSSBE6KJ4TR564526           EMDEN
        N030838 VSSBE6KJ4TR568396           EMDEN
        N030838 VSSBE6KJ7TR563726           EMDEN
        N030838 VSSBE6KJ5TR568309           EMDEN
        N030838 VSSBE6KJ5TR564504           EMDEN
        N030838 VSSBE6KJ4TR564753           EMDEN
        N030838 VSSBE6KJ6TR565418           EMDEN
        N030838 VSSBE6KJ3TR570706           EMDEN
        N030838 VSSBE6KJ4TR569533           EMDEN
        N030838 VSSBE6KJ4TR565661           EMDEN
        N030838 VSSBE6KJ5TR566768           EMDEN
        N030838 VSSBE6KJ5TR565491           EMDEN
        N030838 VSSBE6KJ6TR567153           EMDEN
        N030838 VSSBE6KJ6TR568433           EMDEN
        N030838 VSSBE6KJ4TR567507           EMDEN
        N030838 VSSBE6KJ7TR563239           EMDEN
        N030838 VSSBE6KJ6TR564737           EMDEN
        N030838 VSSBE6KJ5TR565345           EMDEN
        N030838 VSSBE6KJ4TR567202           EMDEN
        N030838 VSSBE6KJ3TR570432           EMDEN
        N030838 VSSBE6KJ6TR567069           EMDEN
        N030838 VSSBE6KJ6TR567170           EMDEN
        N030838 VSSBE6KJ3TR568292           EMDEN
        N030838 VSSBE6KJ6TR563295           EMDEN
        N030838 VSSBE6KJ6TR569677           EMDEN
        N030838 VSSBE6KJ4TR565370           EMDEN
        N030838 VSSBE6KJ5TR567628           EMDEN
        N030838 VSSBE6KJ6TR567105           EMDEN
        N030838 VSSBE6KJ4TR567376           EMDEN
        N030838 VSSBE6KJ5TR567158           EMDEN
        N030838 VSSBE6KJ6TR567380           EMDEN
        N030838 VSSBE6KJ3TR569703           EMDEN
        N030838 VSSBE6KJ5TR570156           EMDEN
        N030838 VSSBE6KJ5TR570125           EMDEN
        N030838 VSSBE6KJ5TR569721           EMDEN
        N030838 VSSBE6KJ4TR569645           EMDEN
        N030838 VSSBE6KJ6TR567489           EMDEN
        N030838 VSSBE6KJ5TR563224           EMDEN
        N030838 VSSBE6KJ6TR569629           EMDEN
        N030838 VSSBE6KJ3TR568423           EMDEN
        N030838 VSSBE6KJ4TR566776           EMDEN
        N030838 VSSBE6KJ6TR564169           EMDEN
        N030838 VSSBE6KJ4TR568673           EMDEN
        N030838 VSSBE6KJ3TR569121           EMDEN
        N030838 VSSBE6KJ3TR569748           EMDEN
        N030838 VSSBE6KJ6TR569078           EMDEN
        N030838 VSSBE6KJ4TR568236           EMDEN
        N030838 VSSBE6KJ4TR569726           EMDEN
        N030838 VSSBE6KJ4TR568706           EMDEN
        N030838 VSSBE6KJ5TR567127           EMDEN
        N030838 VSSBE6KJ4TR566826           EMDEN
        N030838 VSSBE6KJ4TR566485           EMDEN
        N030838 VSSBE6KJ5TR568519           EMDEN
        N030838 VSSBE6KJ4TR569970           EMDEN
        N030838 VSSBE6KJ6TR568822           EMDEN
        N030838 VSSBE6KJ4TR568303           EMDEN
        N030838 VSSBE6KJ6TR568884           EMDEN
        N030838 VSSBE6KJ6TR563667           EMDEN
        N030838 VSSBE6KJ4TR565109           EMDEN
        N030838 VSSBE6KJ4TR563716           EMDEN
        N030838 VSSBE6KJ4TR563053           EMDEN
        N030838 VSSBE6KJ6TR565290           EMDEN
        N030838 VSSBE6KJ4TR565305           EMDEN
        N030838 VSSBE6KJ5TR563305           EMDEN
        N030838 VSSBE6KJ4TR568754           EMDEN
        N030838 VSSBE6KJ6TR570151           EMDEN
        N030839 VSSBE6KJ8TR564500           EMDEN
        N030839 VSSBE6KJ9TR567440           EMDEN
        N030839 VSSBE6KJ9TR564540           EMDEN
        N030839 VSSBE6KJ9TR563260           EMDEN
        N030839 VSSBE6KJXTR564742           EMDEN
        N030839 VSSBE6KJ8TR566361           EMDEN
        N030839 VSSBE6KJ9TR567423           EMDEN
        N030839 VSSBE6KJ7TR568702           EMDEN
        N030839 VSSBE6KJ7TR567520           EMDEN
        N030839 VSSBE6KJ7TR565377           EMDEN
        N030839 VSSBE6KJ8TR565095           EMDEN
        N030839 VSSBE6KJXTR564479           EMDEN
        N030839 VSSBE6KJXTR564496           EMDEN
        N030839 VSSBE6KJ7TR568408           EMDEN
        N030839 VSSBE6KJXTR563980           EMDEN
        N030839 VSSBE6KJ9TR565395           EMDEN
        N030839 VSSBE6KJ9TR566708           EMDEN
        N030839 VSSBE6KJXTR564224           EMDEN
        N030839 VSSBE6KJ7TR570448           EMDEN
        N030839 VSSBE6KJ7TR568280           EMDEN
        N030839 VSSBE6KJ7TR569543           EMDEN
        N030839 VSSBE6KJ9TR570483           EMDEN
        N030839 VSSBE6KJ9TR564294           EMDEN
        N030839 VSSBE6KJ8TR564884           EMDEN
        N030839 VSSBE6KJ9TR564487           EMDEN
        N030839 VSSBE6KJXTR566989           EMDEN
        N030839 VSSBE6KJXTR567401           EMDEN
        N030839 VSSBE6KJ7TR569736           EMDEN
        N030839 VSSBE6KJ9TR568149           EMDEN
        N030839 VSSBE6KJ7TR569753           EMDEN
        N030839 VSSBE6KJ8TR566473           EMDEN
        N030839 VSSBE6KJ9TR567941           EMDEN
        N030839 VSSBE6KJ7TR564634           EMDEN
        N030839 VSSBE6KJXTR563851           EMDEN
        N030839 VSSBE6KJ8TR565839           EMDEN
        N030839 VSSBE6KJ9TR569060           EMDEN
        N030839 VSSBE6KJ8TR568689           EMDEN
        N030839 VSSBE6KJ9TR563291           EMDEN
        N030839 VSSBE6KJ7TR567386           EMDEN
        N030839 VSSBE6KJ7TR568182           EMDEN
        N030839 VSSBE6KJXTR564515           EMDEN
        N030839 VSSBE6KJ9TR567809           EMDEN
        N030839 VSSBE6KJ9TR564506           EMDEN
        N030839 VSSBE6KJ7TR569526           EMDEN
        N030839 VSSBE6KJXTR563218           EMDEN
        N030839 VSSBE6KJ9TR566496           EMDEN
        N030839 VSSBE6KJ7TR569025           EMDEN
        N030839 VSSBE6KJ9TR566661           EMDEN
        N030839 VSSBE6KJ8TR567803           EMDEN
        N030839 VSSBE6KJXTR566247           EMDEN
        N030839 VSSBE6KJXTR566491           EMDEN
        N030839 VSSBE6KJ9TR568619           EMDEN
        N030839 VSSBE6KJ9TR568524           EMDEN
        N030839 VSSBE6KJ8TR567378           EMDEN
        N030839 VSSBE6KJ7TR569218           EMDEN
        N030839 VSSBE6KJ9TR566501           EMDEN
        N030839 VSSBE6KJ8TR568613           EMDEN
        N030839 VSSBE6KJ7TR567968           EMDEN
        N030839 VSSBE6KJ9TR563565           EMDEN
        N030839 VSSBE6KJ8TR568286           EMDEN
        N030839 VSSBE6KJXTR567351           EMDEN
        N030839 VSSBE6KJXTR566782           EMDEN
        N030839 VSSBE6KJ7TR567646           EMDEN
        N030839 VSSBE6KJ7TR568263           EMDEN
        N030839 VSSBE6KJ9TR568362           EMDEN
        N030839 VSSBE6KJXTR566572           EMDEN
        N030839 VSSBE6KJ8TR568868           EMDEN
        N030839 VSSBE6KJ7TR567775           EMDEN
        N030839 VSSBE6KJ7TR565072           EMDEN
        N030839 VSSBE6KJXTR567396           EMDEN
        N030840 VSSBE6KJXTR570346           EMDEN
        N030840 VSSBE6KJXTR568919           EMDEN
        N030840 VSSBE6KJXTR569651           EMDEN
        N030840 VSSBE6KJXTR570427           EMDEN
        N030840 VSSBE6KJXTR569004           EMDEN
        N030841 VSSBF6KJ6TR563309           EMDEN
        N030841 VSSBF6KJ7TR566431           EMDEN
        N030841 VSSBF6KJ9TR563272           EMDEN
        N030841 VSSBF6KJ3TR565499           EMDEN
        N030841 VSSBF6KJ9TR568200           EMDEN
        N030841 VSSBF6KJ8TR568219           EMDEN
        N030841 VSSBF6KJ9TR563711           EMDEN
        N030841 VSSBF6KJ7TR563299           EMDEN
        N030841 VSSBF6KJ5TR568890           EMDEN
        N030841 VSSBF6KJ1TR569292           EMDEN
        N030841 VSSBF6KJ4TR569769           EMDEN
        N030841 VSSBF6KJ6TR568963           EMDEN
        N030841 VSSBF6KJXTR570716           EMDEN
        N030841 VSSBF6KJ0TR569588           EMDEN
        N030841 VSSBF6KJXTR569808           EMDEN
        N030841 VSSBF6KJ2TR564490           EMDEN
        N030841 VSSBF6KJ3TR570752           EMDEN
        N030841 VSSBF6KJ2TR570659           EMDEN
        N030841 VSSBF6KJ4TR570386           EMDEN
        N030841 VSSBF6KJ6TR563990           EMDEN
        N030841 VSSBF6KJ3TR567382           EMDEN
        N030841 VSSBF6KJ2TR568877           EMDEN
        N030841 VSSBF6KJ3TR569634           EMDEN
        N030841 VSSBF6KJXTR569114           EMDEN
        N030841 VSSBF6KJ0TR567100           EMDEN
        N030841 VSSBF6KJ0TR571812           EMDEN
        N030841 VSSBF6KJ2TR567857           EMDEN
        N030841 VSSBF6KJ6TR563035           EMDEN
        N030841 VSSBF6KJXTR564494           EMDEN
        N030841 VSSBF6KJ0TR568151           EMDEN
        N030841 VSSBF6KJ7TR568227           EMDEN
        N030841 VSSBF6KJ4TR570453           EMDEN
        N030841 VSSBF6KJ6TR567179           EMDEN
        N030841 VSSBF6KJXTR567122           EMDEN
        N030841 VSSBF6KJ1TR563847           EMDEN
        N030841 VSSBF6KJ4TR564622           EMDEN
        N030841 VSSBF6KJ2TR567132           EMDEN
        N030841 VSSBF6KJ8TR564218           EMDEN
        N030841 VSSBF6KJ5TR563933           EMDEN
        N030841 VSSBF6KJ3TR568810           EMDEN
        N030841 VSSBF6KJ7TR564498           EMDEN
        N030841 VSSBF6KJ2TR563274           EMDEN
        N030841 VSSBF6KJ4TR571618           EMDEN
        N030841 VSSBF6KJXTR568268           EMDEN
        N030841 VSSBF6KJ3TR567091           EMDEN
        N030841 VSSBF6KJ8TR566468           EMDEN
        N030841 VSSBF6KJ1TR571785           EMDEN
        N030841 VSSBF6KJ3TR567768           EMDEN
        N030841 VSSBF6KJXTR563345           EMDEN
        N030841 VSSBF6KJ5TR569618           EMDEN
        N030841 VSSBF6KJ7TR564520           EMDEN
        N030841 VSSBF6KJ0TR563886           EMDEN
        N030841 VSSBF6KJ9TR563336           EMDEN
        N030841 VSSBF6KJ6TR569689           EMDEN
        N030841 VSSBF6KJ6TR570759           EMDEN
        N030841 VSSBF6KJXTR563927           EMDEN
        N030842 VSSDE6KJ0TR564161           EMDEN
        N030842 VSSDE6KJ1TR566730           EMDEN
        N030842 VSSDE6KJ1TR566971           EMDEN
        N030842 VSSDE6KJ0TR566198           EMDEN
        N030842 VSSDE6KJ1TR566176           EMDEN
        N030842 VSSDE6KJ1TR566856           EMDEN
        N030842 VSSDE6KJ0TR568243           EMDEN
        N030842 VSSDE6KJ0TR565147           EMDEN
        N030842 VSSDE6KJ2TR563786           EMDEN
        N030842 VSSDE6KJ1TR566873           EMDEN
        N030842 VSSDE6KJ2TR563559           EMDEN
        N030842 VSSDE6KJ1TR568154           EMDEN
        N030842 VSSDE6KJ1TR570518           EMDEN
        N030842 VSSDE6KJ1TR563939           EMDEN
        N030842 VSSDE6KJ0TR566055           EMDEN
        N030842 VSSDE6KJ2TR566784           EMDEN
        N030842 VSSDE6KJ1TR563276           EMDEN
        N030842 VSSDE6KJ1TR566727           EMDEN
        N030842 VSSDE6KJ2TR564310           EMDEN
        N030842 VSSDE6KJ1TR574777           EMDEN
        N030842 VSSDE6KJ2TR566106           EMDEN
        N030842 VSSDE6KJ1TR562886           EMDEN
        N030842 VSSDE6KJ0TR564466           EMDEN
        N030842 VSSDE6KJ1TR569384           EMDEN
        N030842 VSSDE6KJ0TR563270           EMDEN
        N030842 VSSDE6KJ2TR566123           EMDEN
        N030842 VSSDE6KJ2TR563626           EMDEN
        N030842 VSSDE6KJ1TR570681           EMDEN
        N030842 VSSDE6KJ1TR571460           EMDEN
        N030842 VSSDE6KJ1TR570910           EMDEN
        N030842 VSSDE6KJ0TR570560           EMDEN
        N030842 VSSDE6KJ0TR566704           EMDEN
        N030842 VSSDE6KJ1TR563312           EMDEN
        N030842 VSSDE6KJ1TR570938           EMDEN
        N030842 VSSDE6KJ1TR563844           EMDEN
        N030842 VSSDE6KJ1TR563889           EMDEN
        N030842 VSSDE6KJ2TR563285           EMDEN
        N030842 VSSDE6KJ0TR571983           EMDEN
        N030842 VSSDE6KJ0TR564130           EMDEN
        N030842 VSSDE6KJ1TR571894           EMDEN
        N030842 VSSDE6KJ0TR563303           EMDEN
        N030842 VSSDE6KJ0TR568095           EMDEN
        N030842 VSSDE6KJ1TR568011           EMDEN
        N030842 VSSDE6KJ0TR571448           EMDEN
        N030842 VSSDE6KJ0TR569392           EMDEN
        N030842 VSSDE6KJ1TR570552           EMDEN
        N030842 VSSDE6KJ0TR565584           EMDEN
        N030842 VSSDE6KJ2TR566848           EMDEN
        N030842 VSSDE6KJ2TR564355           EMDEN
        N030842 VSSDE6KJ0TR570493           EMDEN
        N030842 VSSDE6KJ0TR563611           EMDEN
        N030842 VSSDE6KJ0TR563706           EMDEN
        N030842 VSSDE6KJ1TR568106           EMDEN
        N030842 VSSDE6KJ2TR566140           EMDEN
        N030842 VSSDE6KJ0TR570722           EMDEN
        N030842 VSSDE6KJ0TR563849           EMDEN
        N030842 VSSDE6KJ0TR567917           EMDEN
        N030842 VSSDE6KJ0TR568128           EMDEN
        N030842 VSSDE6KJ2TR566218           EMDEN
        N030842 VSSDE6KJ0TR570901           EMDEN
        N030842 VSSDE6KJ1TR563701           EMDEN
        N030842 VSSDE6KJ2TR566221           EMDEN
        N030842 VSSDE6KJ2TR566235           EMDEN
        N030842 VSSDE6KJ0TR571577           EMDEN
        N030842 VSSDE6KJ1TR570437           EMDEN
        N030842 VSSDE6KJ0TR568677           EMDEN
        N030842 VSSDE6KJ1TR568185           EMDEN
        N030842 VSSDE6KJ0TR568078           EMDEN
        N030842 VSSDE6KJ0TR571899           EMDEN
        N030842 VSSDE6KJ0TR568193           EMDEN
        N030843 VSSDE6KJ3TR566096           EMDEN
        N030843 VSSDE6KJ4TR566074           EMDEN
        N030843 VSSDE6KJ4TR563580           EMDEN
        N030843 VSSDE6KJ3TR574781           EMDEN
        N030843 VSSDE6KJ3TR569256           EMDEN
        N030843 VSSDE6KJ4TR566186           EMDEN
        N030843 VSSDE6KJ3TR563621           EMDEN
        N030843 VSSDE6KJ3TR563960           EMDEN
        N030843 VSSDE6KJ2TR574688           EMDEN
        N030843 VSSDE6KJ3TR569399           EMDEN
        N030843 VSSDE6KJ4TR571405           EMDEN
        N030843 VSSDE6KJ3TR570956           EMDEN
        N030843 VSSDE6KJ3TR564154           EMDEN
        N030843 VSSDE6KJ4TR569444           EMDEN
        N030843 VSSDE6KJ3TR574232           EMDEN
        N030843 VSSDE6KJ2TR571919           EMDEN
        N030843 VSSDE6KJ2TR568986           EMDEN
        N030843 VSSDE6KJ4TR570805           EMDEN
        N030843 VSSDE6KJ2TR570513           EMDEN
        N030843 VSSDE6KJ2TR568065           EMDEN
        N030843 VSSDE6KJ3TR565594           EMDEN
        N030843 VSSDE6KJ3TR574375           EMDEN
        N030843 VSSDE6KJ3TR571640           EMDEN
        N030843 VSSDE6KJ3TR574425           EMDEN
        N030843 VSSDE6KJ4TR563840           EMDEN

In [ ]:
import importlib
import boat_analysis
importlib.reload(boat_analysis)
from boat_analysis import *

results = run_full_analysis(dfAllBoats, dfExtraccion, dfFacturasFaltantes)